import type { Issue } from "./types"

export const issues: Issue[] = [
  {
    id: "issue-1",
    title: "Fix broken login redirect flow",
    description: "Users are experiencing a broken redirect after logging in. Investigate auth flow and router logic.",
    status: "To Do",
    priority: "High",
    type: "Bug",
    storyPoints: 5,
    assigneeId: "person-1",
    projectId: "proj-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "issue-2",
    title: "Improve performance on dashboard graphs",
    description: "Dashboard graphs lag on large datasets. Explore chart rendering or data aggregation issues.",
    status: "In Progress",
    priority: "Critical",
    type: "Task",
    storyPoints: 8,
    assigneeId: "person-2",
    projectId: "proj-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "issue-3",
    title: "Implement drag-and-drop on Kanban",
    description: "Enable drag-and-drop interaction between columns on the Kanban board.",
    status: "In Progress",
    priority: "Medium",
    type: "Feature",
    storyPoints: 6,
    assigneeId: "person-3",
    projectId: "proj-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "issue-4",
    title: "Resolve issue with timezone conversion",
    description: "Some users report incorrect due dates due to timezone misalignment. Validate server/client conversion.",
    status: "To Do",
    priority: "High",
    type: "Bug",
    storyPoints: 3,
    assigneeId: "person-4",
    projectId: "proj-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "issue-5",
    title: "Add dark mode toggle to navbar",
    description: "Add a dark/light toggle and persist theme preference in local storage.",
    status: "Done",
    priority: "Low",
    type: "Feature",
    storyPoints: 2,
    assigneeId: "person-1",
    projectId: "proj-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "issue-6",
    title: "Optimize API payloads for team data",
    description: "Reduce unused fields in API payload for team-related queries.",
    status: "Blocked",
    priority: "Medium",
    type: "Task",
    storyPoints: 4,
    assigneeId: "person-2",
    projectId: "proj-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]